import Image from "next/image";
import React from "react";

export const metadata = {
  title: "Starecords - About Us",
  description: "Generated by create next app",
};

const Layout = ({ children }) => {
  return (
    <section className="w-full h-hull">
      <div className="relative w-full h-[400px]  ">
        <Image
          src="/SRE.png"
          alt=""
          fill={true}
          priority={true}
          className="object-cover object-top grayscale-[100]"
        />
        <h1 className="text-3xl md:text-5xl text-zinc-900 dark:text-zinc-200 uppercase bg-zinc-900/20 backdrop-blur-lg py-2 px-5 w-full text-center absolute bottom-0 font-[Coco]">
          About Us
        </h1>
      </div>
      {children}
    </section>
  );
};

export default Layout;
