import React from "react";

export const metadata = {
  title: "Starecords - Contact",
  description: "Generated by create next app",
};

const Contact = () => {
  return <div className="pt-14">Contact</div>;
};

export default Contact;
