import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import Footer from '@/components/footer/Footer'
import { Poppins } from 'next/font/google'
import { ThemeProvider } from '@/context/ThemeContext'
import Wave from '@/components/Wave/wave'




const poppins = Poppins({ subsets: ['latin'], weight: ["400", "800"], crossOrigin: "true" })




export const metadata = {

  title: 'Starecords',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {




  return (
    <html lang="en">
      <body className={` ${poppins.className}`}>
        <Wave />
        <ThemeProvider  >
          <div className='pt-20 relative z-50  min-h-screen flex flex-col justify-between w-full max-w-6xl mx-auto '>
            <Navbar />
            {children}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
