import React from "react";

import axios from "axios";
import Link from "next/link";
import Image from "next/legacy/image";

export const metadata = {
  title: "Starecords - Merchant",
  description: "Generated by create next app",
};

async function getData() {
  const response = await axios.get(
    "https://ticket-server.webqodes.com/merchants",
    {
      cache: "no-store",
    }
  );
  return response.data;
}

const Portfolio = async () => {
  const data = await getData();

  return (
    <>
      <div className="w-full h-full py-16 px-4 md:px-0 ">
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-5 md:gap-2">
          {data.map((item) => (
            <div
              key={item.id}
              className="shadow-xl shadow-black/10 py-4 card w-full  mx-auto glass"
            >
              <figure>
                <Image
                  src={item.url}
                  alt={item.title}
                  width={1000}
                  height={700}
                  placeholder="blur"
                  blurDataURL={item.url}
                  priority={true}
                  className="object-cover"
                />
              </figure>
              <div className="card-body text-sm">
                <div className=" flex items-start justify-between ">
                  <h2 className="card-title w-full mb-2">{item.title}</h2>
                  <p className="text-right p-1 px-2 shadow-lg shadow-black/20 bg-slate-900/70 rounded-xl text-sm text-zinc-300 w-max">
                    Rp.{item.price}
                  </p>
                </div>
                <div className="py-3">
                  <h3>Description :</h3>
                  <p>{item.desc}</p>
                </div>
                <div className="card-actions justify-end">
                  <Link
                    href={`https://api.whatsapp.com/send?phone=6287826702424&text=hallo%20admin%20saya%20mau%20pesan%20${item.title}`}
                    className="btn btn-md bg-blend-darken w-full mx-auto"
                  >
                    <span className="text-sm font-sans">order</span>
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default Portfolio;
